### ISSUE TITLE
Sensori tapparella

### ISSUE THREAD

**Issue by FAKKIUZ** [lcavalli/esp-kyo-alarm-generic#2]
Ciao! Complimenti per il progetto!
I sensori delle tapparelle li devo mappare con device class motion? Oppure posso assegnare un sistema binario diverso di Home Assistant per tenerle separate dal sensore di movimento, per esempio "moving"?
Grazie!

**Comment by amastrogiacomo1968** [comment]
Io l'ho mappato, non so se sia corretto, come device_class: window

**Comment by FAKKIUZ** [comment]
Grazie, però il sensore non credo legga l'apertura e la chiusura della tapparella, ma solo se viene mossa. Per quel motivo volevo tenere questi sensori separati dagli altri.

**Comment by lcavalli** [comment]
Ciao, grazie per i complimenti!
La device class in effetti la puoi impostare ad uno qualsiasi dei valori ammessi per i binary sensor di Home Assistant, come elencato qui: https://www.home-assistant.io/integrations/binary_sensor/#device-class. Questo fa si che l'icona sia specifica per lo stato `on` e `off` e la rappresentazione testuale sia consistente con il sensore. Per un sensore tapparella (che comunque è sempre un sensore binario) però non mi pare ci sia una device class appropriata. Mi vengono in mente solo 3 possibili soluzioni oltre a quella suggerita da @amastrogiacomo1968 e cioè di usare `window`:

1. Imposti una device class `moving`, l'icona forse non è perfetta ma la rappresentazione testuale mi sembra calzante.
2. Non imposti la device class e lasci il sensore generico, poi in Home Assistant assegni l'icona che preferisci, ad esempio `mdi:window-shutter`
3. Crei in Home Assistant un template binary sensor il cui valore è preso dal sensore fornito dall'integrazione, ma l'icona è assegnata dinamicamente in base al valore come indicato in questo esempio: https://www.home-assistant.io/integrations/template/#change-the-icon-when-a-state-changes

**Comment by FAKKIUZ** [comment]
Molto esaustivo, grazie mille!
