### ISSUE TITLE
KYO model request failed

### ISSUE THREAD

**Issue by antonioromito** [lcavalli/esp-kyo-alarm-generic#3]
Ciao, intanto ti ringrazio per aver condiviso il progetto e ringrazio Lorenzo per il suo lavoro iniziale.

Ho flashato inizialmente il mio D1 mini pro configurato in tutte le parti da customizzare ed inizialmente funziona (quasi) tutto nel senso che in HA vedevo lo stato di tutti i sensori dal dispositivo ESPHome. 
Unica cosa che non avevo configurato era la parte della password API. 
Dato che non stavo cercando di far funzionare il template per armare o disarmare l'allarme con pin, allora ho pensato di riflashare il mio D1 mini pro aggiungendo anche la parte relativa alla password delle API. 
Da qui sono iniziati i problemi "seri". Una volta riflashato il device sembra che non riesca più a comunicare con la centrale:

Qui trovi l'output del log --> https://pastebin.com/MYJ9wrvT

Immagino che la causa sia quel:

```
[17:41:11][E][esp-key-alarm:357]: KYO model request failed
[17:41:11][V][component:199]: Component custom_component took a long time for an operation (0.11 s).
[17:41:11][V][component:200]: Components should block for at most 20-30ms.
```

Sapresti aiutarmi?

**Comment by lcavalli** [comment]
Prego!
Riguardo al tuo problema, sembra che la centrale, a seguito della richiesta fatta, non invii la risposta e il loop si blocca in attesa di ricevere almeno 6 byte. Il framework si accorge e stampa nel log quel messaggio. Puoi provare alcune cose:
1 Se hai attivato il menù col codice installatore non comunica sulla seriale. Devi prima uscire.
2. Prova a fare notare e uscire dal menu con il codice installatore
3. Nei dettagli dell'integrazione in HA dovresti avere un pulsante che fa il reset dell'esp8266, puoi provare a cliccarlo.
4. Controlla che il connettore seriale sia inserito bene (come ultima spiaggia, è improbabile che si sia mosso se prima andava)

**Comment by antonioromito** [comment]
Grazie per la risposta Luca. Alla fine simulando la chiusura della centrale e la riapertura con tamper e codice installatore seguendo la procedura ha ripreso a funzionare correttamente.
