### ISSUE TITLE
Aggiornamento OTA fallisce

### ISSUE THREAD

**Issue by lcavalli** [lcavalli/esp-kyo-alarm-generic#4]
L'aggiornamento OTA spesso rallenta fino a fermarsi e quindi fallisce. In questo caso l'esp8266 si resetta e si riavvia.
Un possibile warkaround temporaneo è quello di fare più tentativi consecutivi di aggiornamento in modo da riuscire a completarlo quando viene fatto alla fine del boot, ma prima di iniziare l'esecuzione.

**Comment by antonioromito** [comment]
Confermo stesso problema. Io ho trovato come unica soluzione quella di farlo via USB purtroppo

**Comment by lcavalli** [comment]
Si, anche io all'inizio aprivo e flashavo da USB (fatto decine di volte durante lo sviluppo). Se adesso faccio qualche tentativo alla fine becco il momento giusto e l'aggiornamento funziona. Devo capire cosa non sta funzionando.

**Comment by lorenzo-deluca** [comment]
Ciao, io ho "risolto" così: https://github.com/lorenzo-deluca/espkyogate/issues/16#issuecomment-1093225720
In pratica sembra che dalle ultime versioni di ESPHome il componente uart_bus interferisca con gli aggiornamenti OTA.
Ne parlano anche qui https://github.com/esphome/issues/issues/2629

**Comment by lcavalli** [comment]
Ciao @lorenzo-deluca, stavo seguendo la issue nel tuo tempo. Si, penso che la tua soluzione di andare in safe prima di un aggiornamento OTA sia la cosa migliore. Avevo anche provato a intercettare l'inizio dell'aggiornamento OTA e fermare la trasmissione UART ma senza successo. Grazie.

**Comment by lcavalli** [comment]
A partire dalla versione 2022.5.0 di ESPHome (io ho provato con la versione 2022.5.1) sembra che il problema non sia più presente.
