### ISSUE TITLE
Allarme

### ISSUE THREAD

**Issue by FAKKIUZ** [lcavalli/esp-kyo-alarm-generic#6]
Ciao Luca, rinnovo i complimenti per il progetto.
Volevo chiedere se è presente un sensore binario che indichi che l'allarme sta suonando, così da creare un'automazione che mandi una notifica.
Grazie!

**Comment by lcavalli** [comment]
Grazie.
Per fare quello che vuoi tu non serve un sensore aggiuntivo, basta un'automazione tipo questa:

```yaml
alias: Notifica allarme attivo
description: ''
trigger:
  - platform: state
    entity_id: alarm_control_panel.kyo_alarm
    to: triggered
condition: []
action:
  - service: notify.famiglia
    data:
      title: Allarme
      message: Allarme scattato a casa
mode: single```

**Comment by FAKKIUZ** [comment]
Grazie mille!
